framework:
    notifier:
        chatter_transports:
        texter_transports:
            vonage: '%env(VONAGE_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/vonage
            urgent: ['email', 'sms']
            high: ['email', 'sms']
            medium: ['email']
            low: ['email']
